import type { Metadata } from "next";
import { navbarLinks } from "@/config/navbar";
import { MainNav } from "@/components/main-nav";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Simpe-Next-Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen antialiased`}
      >
        <header>
          <MainNav items={navbarLinks.main} />
        </header>
        <main className="flex-1 py-32">{children}</main>
      </body>
    </html>
  );
}
